- name: TOML is present
  copy:
    src=bdd.toml
    dest=/etc/confd/conf.d/bdd.toml
  tags: [bdd]
- name: Config template is present
  copy:
    src=bdd.conf.tmpl
    dest=/etc/confd/templates/bdd.conf.tmpl
  tags: [bdd]
- name: Deployment script is present
  copy:
    src=deploy-bdd.sh
    dest=/usr/local/bin/deploy-bdd.sh
    mode="0755"
  tags: [bdd]
- name: Deployment is run
  shell: deploy-bdd.sh
  tags: [bdd]